bugfix footer
WildCodeSchool/orleans-0217-sourcink pull request #65
Opened 2017-07-11 13:56 UTC by dbdylan

2017-07-11 14:02 UTC, sblondeau requested changes

2017-07-11 14:02 UTC, sblondeau commented on src/AppBundle/Resources/views/Base/footer.html.twig
> +                    <br/>
PAS DE BR !!!!

2017-07-11 14:02 UTC, sblondeau commented on src/AppBundle/Resources/views/Base/footer_premium.html.twig
> +                    <br/>
pas de br !

2017-07-11 14:02 UTC, sblondeau commented on src/AppBundle/Resources/views/Base/footer_premium.html.twig
>              <div class="col l4 offset-l2 s12">
euh, je peux savoir pourquoi il y a 2 footer différents ? c'est sans doute pas à cause d'une couleur de fond qui change et qui se règle en 1 ligne de CSS ?

2017-07-11 14:19 UTC, sblondeau requested changes
je veux que tu me vires le fichier footer_premium !

2017-07-13 07:51 UTC, dbdylan commented
fichier footer supprimer

2017-07-13 09:34 UTC, open-it approved these changes

2017-07-13 09:34 UTC, merged